### ISSUE TITLE
Build instructions not working

### ISSUE THREAD

**Issue by monali45** [apache/polaris#1916]
### Describe the bug

I m using quickstart guide, to install polaris in my GCP VM

```
export ASSETS_PATH=$(pwd)/getting-started/assets/
export QUARKUS_DATASOURCE_JDBC_URL=$(printf '%s' "jdbc:postgresql://<host:port>/postgres")
export QUARKUS_DATASOURCE_USERNAME=polaris
export QUARKUS_DATASOURCE_PASSWORD=<my-password>
export CLIENT_ID=<my-client>
export CLIENT_SECRET=<my-secret>

echo $QUARKUS_DATASOURCE_JDBC_URL

GCS_BUCKET_NAME=<my-bucket>
echo "GCS Bucket Name: $GCS_BUCKET_NAME"

export STORAGE_LOCATION="gs://$GCS_BUCKET_NAME/quickstart_catalog/"

# got this command from deploy-gcp.sh
./gradlew clean :polaris-server:assemble :polaris-admin:assemble \
       -Dquarkus.container-image.tag=postgres-latest \
       -Dquarkus.container-image.build=true \
       --no-build-cache --stacktrace --debug

OR

# command from quickstart guide
./gradlew clean \
  :polaris-server:assemble \
  :polaris-server:quarkusAppPartsBuild \
  :polaris-admin:assemble --rerun \
  -Dquarkus.container-image.tag=postgres-latest \
  -Dquarkus.container-image.build=true

```

### To Reproduce

Use same commands as description

### Actual Behavior

Error after gradle clean cmd:
```

2025-06-20T14:11:07.189+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2025-06-20T14:11:07.191+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
2025-06-20T14:11:07.191+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2025-06-20T14:11:07.191+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
2025-06-20T14:11:07.191+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':polaris-admin:quarkusAppPartsBuild'.
2025-06-20T14:11:07.191+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > There was a failure while executing work items
2025-06-20T14:11:07.191+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
2025-06-20T14:11:07.192+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]       > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2025-06-20T14:11:07.192+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           [error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromJar threw an exception: java.lang.RuntimeException: Unable to build container image. Please check your docker installation.
...
2025-06-20T14:11:07.192+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at java.base/java.lang.Thread.run(Thread.java:1583)
2025-06-20T14:11:07.192+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]           at org.jboss.threads.JBossThread.run(JBossThread.java:499)
2025-06-20T14:11:07.192+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2025-06-20T14:11:07.192+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2025-06-20T14:11:07.192+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
2025-06-20T14:11:07.192+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Run with --scan to get full insights.
2025-06-20T14:11:07.193+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Get more help at https://help.gradle.org.
2025-06-20T14:11:07.193+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
2025-06-20T14:11:07.193+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
2025-06-20T14:11:07.193+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':polaris-admin:quarkusAppPartsBuild'.
2025-06-20T14:11:07.193+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at 
....
2025-06-20T14:11:07.196+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.workers.WorkerExecutionException: There was a failure while executing work items
2025-06-20T14:11:07.196+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.workers.internal.DefaultWorkerExecutor.workerExecutionException(DefaultWorkerExecutor.java:223)
2025-06-20T14:11:07.196+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 

....

2025-06-20T14:11:07.341+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
2025-06-20T14:11:07.341+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   [error]: Build step io.quarkus.container.image.docker.deployment.DockerProcessor#dockerBuildFromJar threw an exception: java.lang.RuntimeException: Unable to build container image. Please check your docker installation.
2025-06-20T14:11:07.341+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.container.image.docker.common.deployment.CommonProcessor.buildFromJar(CommonProcessor.java:67)
2025-06-20T14:11:07.341+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.container.image.docker.deployment.DockerProcessor.dockerBuildFromJar(DockerProcessor.java:62)
io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:161)
2025-06-20T14:11:07.342+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:368)
2025-06-20T14:11:07.342+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   ... 24 more
2025-06-20T14:11:07.342+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.RuntimeException: Unable to build container image. Please check your docker installation.
2025-06-20T14:11:07.342+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at io.quarkus.container.image.docker.common.deployment.CommonProcessor.buildFromJar(CommonProcessor.java:67)
```

### Expected Behavior

Should build polaris without errors

### System information

using GCP VM(Debian 12) & AlloyDB 

Git version: git version 2.39.5
Docker version: Docker version 28.2.2, build e6534b4
Java version: openjdk version "21.0.7" 2025-04-15 LTS
jq version: jq-1.6

**Comment by adutra** [comment]
Hi @monali45 can you double-check that you have a valid Docker daemon running?

What is the output of the following commands?
 
```shell
docker build -f runtime/server/src/main/docker/Dockerfile.jvm -t docker.io/apache/polaris:postgres-latest runtime/server
docker build -f runtime/admin/src/main/docker/Dockerfile.jvm -t docker.io/apache/polaris-admin-tool:postgres-latest runtime/admin
```

**Comment by monali45** [comment]
Hi @adutra 

Both commands run fine:
```

sudo docker build -f runtime/server/src/main/docker/Dockerfile.jvm -t docker.io/apache/polaris:postgres-latest runtime/server
[+] Building 8.4s (15/15) FINISHED                                      docker:default
 => [internal] load build definition from Dockerfile.jvm                          0.0s
 => => transferring dockerfile: 2.10kB                                            0.0s
 => [internal] load metadata for registry.access.redhat.com/ubi9/openjdk-21-runt  0.3s
 => [internal] load .dockerignore                                                 0.0s
 => => transferring context: 2B                                                   0.0s
 => [ 1/10] FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.22-1.17494  0.0s
 => [internal] load build context                                                 3.0s
 => => transferring context: 214.23MB                                             2.9s
 => CACHED [ 2/10] RUN groupadd --gid 10001 polaris       && useradd --uid 10000  0.0s
 => CACHED [ 3/10] WORKDIR /home/polaris                                          0.0s
 => [ 4/10] COPY --chown=polaris:polaris build/quarkus-app/lib/ /deployments/lib  3.4s
 => [ 5/10] COPY --chown=polaris:polaris build/quarkus-app/*.jar /deployments/    0.0s
 => [ 6/10] COPY --chown=polaris:polaris build/quarkus-app/app/ /deployments/app  0.0s
 => [ 7/10] COPY --chown=polaris:polaris build/quarkus-app/quarkus/ /deployments  0.0s
 => [ 8/10] COPY --chown=polaris:polaris distribution/LICENSE /deployments/       0.1s
 => [ 9/10] COPY --chown=polaris:polaris distribution/NOTICE /deployments/        0.0s
 => [10/10] COPY --chown=polaris:polaris distribution/DISCLAIMER /deployments/    0.0s
 => exporting to image                                                            1.4s
 => => exporting layers                                                           1.4s
 => => writing image sha256:828d528fe1017ab7414490ba4b406213f102c20de7c0c361bfd1  0.0s
 => => naming to docker.io/apache/polaris:postgres-latest                         0.0s
monali_nayak@apache-polaris-dev:~/app/polaris$ sudo docker build -f runtime/admin/src/main/docker/Dockerfile.jvm -t docker.io/apache/polaris-admin-tool:postgres-latest runtime/admin
[+] Building 1.9s (15/15) FINISHED                                      docker:default
 => [internal] load build definition from Dockerfile.jvm                          0.0s
 => => transferring dockerfile: 2.11kB                                            0.0s
 => [internal] load metadata for registry.access.redhat.com/ubi9/openjdk-21-runt  0.3s
 => [internal] load .dockerignore                                                 0.0s
 => => transferring context: 2B                                                   0.0s
 => [internal] load build context                                                 1.5s
 => => transferring context: 111.09MB                                             1.5s
 => [ 1/10] FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.22-1.17494  0.0s
 => CACHED [ 2/10] RUN groupadd --gid 10001 polaris       && useradd --uid 10000  0.0s
 => CACHED [ 3/10] WORKDIR /home/polaris                                          0.0s
 => CACHED [ 4/10] COPY --chown=polaris:polaris build/quarkus-app/lib/ /deployme  0.0s
 => CACHED [ 5/10] COPY --chown=polaris:polaris build/quarkus-app/quarkus-run.ja  0.0s
 => CACHED [ 6/10] COPY --chown=polaris:polaris build/quarkus-app/app/ /deployme  0.0s
 => CACHED [ 7/10] COPY --chown=polaris:polaris build/quarkus-app/quarkus/ /depl  0.0s
 => CACHED [ 8/10] COPY --chown=polaris:polaris distribution/LICENSE /deployment  0.0s
 => CACHED [ 9/10] COPY --chown=polaris:polaris distribution/NOTICE /deployments  0.0s
 => CACHED [10/10] COPY --chown=polaris:polaris distribution/DISCLAIMER /deploym  0.0s
 => exporting to image                                                            0.0s
 => => exporting layers                                                           0.0s
 => => writing image sha256:1a02cba7b6e3460a072b2fa374e251475e7d35cf8892c82bca5b  0.0s
 => => naming to docker.io/apache/polaris-admin-tool:postgres-latest              0.0s
```


Update:
I am using last 2 commands to setup polaris on VM https://github.com/apache/polaris/blob/main/getting-started/assets/cloud_providers/deploy-gcp.sh#L50C1-L55C131

1. Gradle command: 

```
sudo /gradlew clean :polaris-server:assemble :polaris-admin:assemble \
       -Dquarkus.container-image.tag=postgres-latest \
       -Dquarkus.container-image.build=true \
       --no-build-cache
```

Result: getting warnings on gradle cmd, but build is successful:

```
    T extends Object declared in class Builder
/home/monali_nayak/app/polaris/polaris-core/src/main/java/org/apache/polaris/core/config/FeatureConfiguration.java:184: warning: [deprecation] catalogConfigUnsafe(String) in Builder has been deprecated
          .catalogConfigUnsafe("drop-with-purge.enabled")
          ^
  where T is a type-variable:
    T extends Object declared in class Builder
8 warnings

[Incubating] Problems report is available at: file:///home/monali_nayak/app/polaris/build/reports/problems/problems-report.html

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.14.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 2m 31s
136 actionable tasks: 125 executed, 11 up-to-date
```


2. Docker command: 

`sudo docker compose -p polaris -f getting-started/jdbc/docker-compose-bootstrap-db.yml -f getting-started/jdbc/docker-compose.yml up -d`

Result: Variables are assigned but getting warnings. And polaris-polaris-bootstrap-1 container failing to start

```

WARN[0000] The "QUARKUS_DATASOURCE_JDBC_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QUARKUS_DATASOURCE_USERNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QUARKUS_DATASOURCE_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QUARKUS_DATASOURCE_JDBC_URL" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QUARKUS_DATASOURCE_PASSWORD" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CLIENT_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CLIENT_SECRET" variable is not set. Defaulting to a blank string. 
WARN[0000] The "QUARKUS_DATASOURCE_USERNAME" variable is not set. Defaulting to a blank string. 
WARN[0000] The "STORAGE_LOCATION" variable is not set. Defaulting to a blank string. 
WARN[0000] The "AWS_ROLE_ARN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "AZURE_TENANT_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CLIENT_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CLIENT_SECRET" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ASSETS_PATH" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CLIENT_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "CLIENT_SECRET" variable is not set. Defaulting to a blank string. 
WARN[0000] The "ASSETS_PATH" variable is not set. Defaulting to a blank string. 
[+] Running 6/6
 ✔ Network polaris_default                Created                                 0.1s 
 ✘ Container polaris-polaris-bootstrap-1  service "polaris-bootstrap" didn't complete successfully: exit 32.1s aris-1            Create...                               0.0s 
 ✔ Container polaris-polaris-1            Create...                               0.0s 
 ✔ Container polaris-polaris-setup-1      Created                                 0.0s 
 ✔ Container polaris-spark-sql-1          Crea...                                 0.1s 
 ✔ Container polaris-trino-1              Created                                 0.1s 


```

Can you help in above issue ?

**Comment by adutra** [comment]
> Variables are assigned but getting warnings. And polaris-polaris-bootstrap-1 container failing to start

Please make sure your are following the step-by-step guide here:

https://github.com/apache/polaris/blob/0eafcaa4678d85ce9358ba544c02e231b8797eb3/getting-started/jdbc/README.md

I just tried and it worked. I have fewer warnings than you.

**Comment by monali45** [comment]
These instructions seems not working
currently, i'm trying in local machine, 
used "apache-polaris-0.9.0-incubating" tag for stable version

Ran command for tagged 0.9.0 & main branch both:

```
./gradlew clean \
   :polaris-quarkus-server:assemble \
   :polaris-quarkus-server:quarkusAppPartsBuild --rerun \
   :polaris-quarkus-admin:assemble \
   :polaris-quarkus-admin:quarkusAppPartsBuild --rerun \
   -Dquarkus.container-image.tag=postgres-latest \
   -Dquarkus.container-image.build=true
#error
* What went wrong:
Cannot locate tasks that match ':polaris-quarkus-server:assemble' as project 'polaris-quarkus-server' not found in root project 'polaris'.
```

**Comment by dimas-b** [comment]
@monali45 : Server modules got renamed. Please pull the latest code from `main` and re-try.

**Comment by monali45** [comment]
Hi @adutra @dimas-b 

Is there a stable branch or release tag which i can use?
Or a released artifact for jar?

**Comment by dimas-b** [comment]
The 1.0.0 release is in the works: https://github.com/apache/polaris/releases/tag/apache-polaris-1.0.0-incubating-rc0

RC0 vote (with pre-built artifact links): https://lists.apache.org/thread/oh6v2x4g75kw0og6zmyhbtgvp2zh2clb

**Comment by monali45** [comment]
Hi @dimas-b @adutra 

Thank you,
I'm trying to run polaris as standalone, we already have a postgres db.

Below command ran fine:
```
./gradlew clean\
   :polaris-server:assemble \
   :polaris-server:quarkusAppPartsBuild --rerun \
   :polaris-admin:assemble \
   :polaris-admin:quarkusAppPartsBuild --rerun

```

But while running the jar getting error:

```
$ java -jar runtime/server/build/quarkus-build/app/quarkus-app/quarkus-run.jar 

Error: Could not find or load main class io.quarkus.bootstrap.runner.QuarkusEntryPoint
Caused by: java.lang.ClassNotFoundException: io.quarkus.bootstrap.runner.QuarkusEntryPoint
```

There is minimal clear documentation available fro standalone deployment
Can you help here to run polaris jar independently, it would be great

Also, are you guys releasing .jar artifacts somewhere? which we can use directly

**Comment by dimas-b** [comment]
I was able to reproduce the error from the message above (Could not find or load main class) 🤔

**Comment by dimas-b** [comment]
This should work: `java -jar runtime/server/build/quarkus-app/quarkus-run.jar`

**Comment by dimas-b** [comment]
Pre-built jars will be available in the upcoming 1.0.0 release (WIP ATM)

**Comment by monali45** [comment]
Hi @dimas-b 

Thanks! the jar works fine from this location runtime/server/build/quarkus-app/quarkus-run.jar
Do you have tentative release date?

**Comment by dimas-b** [comment]
1.0.0 release is in progress :) RC2 should be open for voting tomorrow, I'd guess.

**Comment by MonkeyCanCode** [comment]
Similar reported by me: https://github.com/apache/polaris/issues/1963

I will update the doc shortly.

**Comment by monali45** [comment]
Hi @adutra  @dimas-b 

can we also have a minimum version requirement matrix for each of the dependencies.
We are planning to use postgres:16, hope it is supported

**Comment by dimas-b** [comment]
@monali45 : I'm not aware of any compatibility guarantees for older PostgreSQL versions. ATM testing is done on PostgreSQL 17, AFAIK.

By all means please let us know if you hit any issues with 16 and we'll try to fix them.

**Comment by monali45** [comment]
Done below steps:

- modified application.properties :

polaris.realm-context.realms=polaris
polaris.persistence.type=relational-jdbc

- ran polaris server with below commad:
```

ENV POLARIS_PERSISTENCE_TYPE=relational-jdbc \
QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://host.docker.internal:5432/polaris \
QUARKUS_DATASOURCE_USERNAME=postgres \
QUARKUS_DATASOURCE_PASSWORD=<my-pg-pass> \
QUARKUS_PROFILE=prod \
JAVA_OPTS="-Xms6g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+ExitOnOutOfMemoryError" \
CLIENT_ID=root \
CLIENT_SECRET=s3cr3t \
STORAGE_LOCATION=gs://iceberg-polaris-test/ \
GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp/gcp-sa.json 

CMD ["java", "-Dquarkus.config.locations=/opt/polaris/config/application.properties", "-jar", "/opt/polaris/quarkus-app/quarkus-run.jar"]

```
- ran admin jar for bootstraping with below command:

```
java \
 -Dquarkus.datasource.jdbc.url=jdbc:postgresql://host.docker.internal:5432/polaris \
 -Dquarkus.datasource.username=postgres \
 -Dquarkus.datasource.password=<my-pg-pass> \
 -Dpolaris.persistence.type=relational-jdbc \
 -Dpolaris.readiness.ignore-severe-issues=true \
 '-Dpolaris.features."ALLOW_INSECURE_STORAGE_TYPES"=true' \
-jar quarkus-run.jar bootstrap  -r  iceberg  -c  iceberg,<my-client>,<my-secret>  --print-credentials
```

- create a catalog using below command:

./polaris --host localhost --port 8181 --client-id <my-client> --client-secret <my-pass> catalogs create --storage-type GCS --default-base-location gs://iceberg-polaris-test/  --allowed-location gs://iceberg-polaris-test/ --service-account /etc/gcp/gcp-sa.json quickstart_catalog

all the above commands ran successfully, but in postgres database - "polaris" there are no schemas
is this expected?

**Comment by dimas-b** [comment]
`polaris_schema` is created by default, but it's not on the PG search path by default.

```
polaris=# \dn
          List of schemas
      Name      |       Owner       
----------------+-------------------
 polaris_schema | postgres
 public         | pg_database_owner
(2 rows)
```

**Comment by flyrain** [comment]
Hi @monali45 , is the issue still there, or can we close it?
